services:
  redis:
    image: redis:7-alpine
    container_name: web_scraping_app_redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
